# .pages.yml — Pages CMS config for Sõiduõppe ABC

media:
  name: images
  label: Pildid
  input: public/images
  output: public/images
  path: ""
  extensions: [png, jpg, jpeg, webp, svg]

settings:
  content:
    merge: true

content:
  # ---------------------
  # SITE DATA
  # ---------------------
  - name: site
    label: Saidi seaded
    type: file
    file: src/data/site.json
    fields:
      - name: name
        label: Autokooli nimi
        type: string
        required: true
      - name: tagline
        label: Peaslogan
        type: string
        required: true
      - name: description
        label: Kirjeldus
        type: text
        required: true
      - name: contact
        label: Kontaktandmed
        type: object
        fields:
          - name: address
            label: Aadress
            type: string
          - name: phone
            label: Telefon
            type: string
          - name: email
            label: E-post
            type: string
          - name: hours
            label: Lahtiolekuajad
            type: string
      - name: usps
        label: Põhieelised (USP-d)
        type: object
        list: true
        fields:
          - name: title
            label: Pealkiri
            type: string
          - name: description
            label: Kirjeldus
            type: text

  # ---------------------
  # COURSES
  # ---------------------
  - name: courses
    label: Kursused
    type: collection
    path: src/content/courses
    filename: "{primary}.md"
    view:
      primary: courseCode
      fields: [courseCode, title, category, price]
      sort: [category, courseCode]
    fields:
      - name: title
        label: Kursuse nimetus
        type: string
        required: true
      - name: courseCode
        label: Kursuse kood
        type: string
        required: true
        description: "Nt: B-ABC7483"
      - name: category
        label: Kategooria
        type: select
        required: true
        options:
          - label: A-kategooria (Mootorratas)
            value: A
          - label: AM-kategooria (Mopeed)
            value: AM
          - label: B-kategooria (Sõiduauto)
            value: B
          - label: BE-kategooria (Auto haagisega)
            value: BE
          - label: C-kategooria (Veoauto)
            value: C
          - label: CE-kategooria (Veoauto haagisega)
            value: CE
          - label: D-kategooria (Buss)
            value: D
          - label: X (Libedasõit jms)
            value: X
      - name: categoryName
        label: Kategooria nimetus
        type: string
        required: true
      - name: description
        label: Kirjeldus
        type: text
      - name: price
        label: Hind
        type: string
        description: "Nt: 1200€"
      - name: priceNote
        label: Hinna märkus
        type: string
      - name: duration
        label: Kestus
        type: string
        description: "Nt: 6 nädalat"
      - name: theoryHours
        label: Teooria tunnid
        type: string
      - name: drivingHours
        label: Sõidutunnid
        type: string
      - name: requirements
        label: Nõuded
        type: string
        list: true
      - name: includes
        label: Hind sisaldab
        type: string
        list: true
      - name: teooriaIframeUrl
        label: Teooria.ee iframe URL
        type: string
        required: true
        description: "Registreerimise iframe URL teooria.ee-st"
      - name: startDate
        label: Alguskuupäev
        type: string
      - name: isFeatured
        label: Esiletõstetud
        type: boolean
      - name: body
        label: Sisu
        type: rich-text

  # ---------------------
  # SERVICES
  # ---------------------
  - name: services
    label: Teenused
    type: collection
    path: src/content/services
    filename: "{primary}.md"
    view:
      primary: title
      fields: [title, type, price]
      sort: [type, title]
    fields:
      - name: title
        label: Teenuse nimetus
        type: string
        required: true
      - name: slug
        label: URL slug
        type: string
        required: true
      - name: description
        label: Kirjeldus
        type: text
        required: true
      - name: shortDescription
        label: Lühikirjeldus
        type: text
      - name: type
        label: Tüüp
        type: select
        required: true
        options:
          - label: Lõppastmekoolitus
            value: loppastme
          - label: Libedasõit
            value: libedasoit
          - label: Ametikoolitus
            value: ametikoolitus
          - label: Muu
            value: other
      - name: price
        label: Hind
        type: string
      - name: duration
        label: Kestus
        type: string
      - name: requirements
        label: Nõuded
        type: string
        list: true
      - name: includes
        label: Hind sisaldab
        type: string
        list: true
      - name: teooriaIframeUrl
        label: Teooria.ee iframe URL (kui on)
        type: string
      - name: body
        label: Sisu
        type: rich-text

  # ---------------------
  # LEGAL
  # ---------------------
  - name: legal
    label: Juriidiline
    type: collection
    path: src/content/legal
    filename: "{primary}.md"
    view:
      primary: page
      fields: [page, pubDate]
      sort: [page]
    fields:
      - name: page
        label: Leht
        type: string
        required: true
      - name: pubDate
        label: Avaldamiskuupäev
        type: date
      - name: body
        label: Sisu
        type: rich-text
